# Global configuration
stages:
  - test

variables:
  LC_CTYPE: 'en_US.UTF-8'

# CI Stage Configuration
yarn_test:
  stage: test
  interruptible: true
  script:
    - docker build --target development -t obschart-py-backend-development . && docker run --rm obschart-py-backend-development ./scripts/test.sh
  tags:
    - docker-buildx
